### Crear un nuevo evento (POST)

POST http://localhost:5000/eventos
Content-Type: application/json

{
  "nombre": "Concierto de Verano",
  "ubicacion": "San Juan, PR",
  "fecha_hora": "2026-06-15 18:00",
  "capacidad": 200,
  "descripcion": "Evento musical al aire libre.",
  "organizador_id": 4
}